### ISSUE TITLE
Store unevaluated expressions

### ISSUE THREAD

**Issue by jasoncpatton** [jasoncpatton/chtc-htcondor-es#5]
We should be able to reconstruct the original ClassAd from its entry in ES when possible. However, we still want ES to be fast, so we cannot mix ClassAd expression strings (which should be unanalyzed text) with other datatypes.

For each attribute in a ClassAd, if it is an expression (i.e. `type(ad[attr]) is classad.ExprTree`), then store the expression under a different field, perhaps `attr + '_Expr'`. Use [matching with dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html#match-unmatch) to make sure all fields matching `*_Expr` are not analyzed.

**Comment by jasoncpatton** [comment]
These `_Expr` fields should also probably not be indexed. Just stored plain with the rest of the job ad.

**Comment by bbockelm** [comment]
What's the benefit here?
