### ISSUE TITLE
Store `LastRemotePool`

### ISSUE THREAD

**Issue by bbockelm** [jasoncpatton/chtc-htcondor-es#8]
It appears `LastRemotePool` isn't recorded in ES but available in `condor_history`:

```
$ condor_history -const 'LastRemotePool isnt undefined' -limit 10 -af LastRemotePool | sort | uniq -c
      5 annex-cm.chtc.wisc.edu
      1 glidein2.chtc.wisc.edu
      4 vultur.ssec.wisc.edu
```

**Comment by jasoncpatton** [comment]
Resolved in https://github.com/jasoncpatton/chtc-htcondor-es/commit/4da29133fc1c94d98f52cd9fcb935a041d7d5bb0
